FROM centos:8
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*

RUN yum update -y && yum install -y python3 python3-pip git wget gcc gcc-c++ make openssl-devel  

WORKDIR /workspace

RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0.tar.gz
RUN tar -xvzf cmake-3.22.0.tar.gz && cd cmake-3.22.0 && ./bootstrap && make -j && make install
RUN pip3 install conan==1.57.0

RUN echo "Welcome to NeuPIMs Simulator!"
FROM centos:8

# Fix CentOS mirror URLs (official CentOS 8 is archived)
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*

# Install basic dependencies
RUN yum update -y && yum install -y \
    python3 python3-pip \
    git wget \
    gcc gcc-c++ \
    make openssl-devel \
    epel-release \
    cmake3

# Use cmake3 as default cmake
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

# Set working directory
WORKDIR /workspace

# Install Conan dependency manager
RUN pip3 install conan==1.57.0

# Simple greeting (optional)
RUN echo "Welcome to NeuPIMs Simulator!"

